# Generated by Django 5.0.6 on 2024-05-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cliente_tecnico_user_cedula_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cedula',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
