# Generated by Django 5.0.6 on 2024-05-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cliente_tecnico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'verbose_name': 'Tecnico', 'verbose_name_plural': 'Tecnicos'},
        ),
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
