# Generated by Django 5.0.4 on 2024-05-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_services'),
        ('users', '0011_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
