# Generated by Django 5.0.4 on 2024-05-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_cliente_user_tecnico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='user',
        ),
    ]
