# Generated by Django 5.0.4 on 2024-05-25 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('fechaHora_esc', models.DateTimeField(auto_now=True)),
                ('fechaHora_vis', models.DateTimeField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('tecnico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tecnico')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
