# Generated by Django 5.0.6 on 2024-05-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical email', 'verbose_name_plural': 'historical Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'email', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
