# Generated by Django 5.0.4 on 2024-05-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cliente_options_alter_tecnico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tecnico',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
