# Generated by Django 5.0.4 on 2024-05-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_cliente_options_alter_tecnico_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
